# Generated by Django 6.0.6 on 2026-07-04 04:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='festver.categoria')),
            ],
            options={
                'verbose_name': 'critério',
                'verbose_name_plural': 'critérios',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('inscricoes_abertas', models.BooleanField(default=False, help_text='Marque para permitir novas inscrições (RF16).')),
                ('votacao_aberta', models.BooleanField(default=False, help_text='Marque para liberar avaliação dos jurados e voto popular.')),
                ('resultados_publicados', models.BooleanField(default=False, help_text='Marque para tornar o pódio visível ao público (RF10).')),
                ('jurados', models.ManyToManyField(blank=True, help_text='Usuários que podem avaliar inscrições deste evento (RF03).', related_name='eventos_como_jurado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='festver.evento'),
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_obra', models.CharField(max_length=200, verbose_name='título da obra')),
                ('arquivo_obra', models.FileField(upload_to='festver/obras/', verbose_name='arquivo da obra')),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('HOM', 'Homologada'), ('REJ', 'Rejeitada')], default='PEN', max_length=3)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='festver.categoria')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes_festver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inscrição',
                'verbose_name_plural': 'inscrições',
            },
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('evento', 'nome')},
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, help_text='Nota de 0 a 10.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_festver', to=settings.AUTH_USER_MODEL)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festver.criterio')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='festver.inscricao')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'unique_together': {('inscricao', 'jurado', 'criterio')},
            },
        ),
        migrations.CreateModel(
            name='VotoPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festver.categoria')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_festver', to=settings.AUTH_USER_MODEL)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_populares', to='festver.inscricao')),
            ],
            options={
                'verbose_name': 'voto popular',
                'verbose_name_plural': 'votos populares',
                'unique_together': {('eleitor', 'categoria')},
            },
        ),
    ]
